# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/delete_comment, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/edit_profile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rename_house, roles: ROLE_ADMIN }
        - { path: ^/add_house, roles: ROLE_ADMIN }
        - { path: ^/delete_house, roles: ROLE_ADMIN }
        - { path: ^/add_book, roles: ROLE_ADMIN }
        - { path: ^/edit, roles: ROLE_ADMIN }
        - { path: ^/delete, roles: ROLE_ADMIN }
        - { path: ^/user_edit, roles: ROLE_ADMIN }
        - { path: ^/user_right, roles: ROLE_ADMIN }
        - { path: ^/user_ban, roles: ROLE_ADMIN }
        - { path: ^/delete_cover, roles: ROLE_ADMIN }
        - { path: ^/area, roles: IS_AUTHENTICATED_FULLY }



    encoders:
          projectBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: projectBundle:User, property: email }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /






