# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    access_control:

        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /rename_house, roles: ROLE_ADMIN }
        - { path: ^/add_house, roles: ROLE_ADMIN }
        - { path: /delete_house, roles: ROLE_ADMIN }
        - { path: ^/add_book, roles: ROLE_ADMIN }
        - { path: /edit, roles: ROLE_ADMIN }
        - { path: /delete, roles: ROLE_ADMIN }


    encoders:
          projectBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: projectBundle:user, property: email }

#        in_memory:
#            memory:
#              users:
#                admin:
#                  password:
#                  roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /






