book_list:
    path:     /
    defaults: { _controller: projectBundle:Default:index }

book_add:
    path: /add_book
    defaults: { _controller: projectBundle:Default:add }

book_view:
    path:     /{id}
    defaults: { _controller: projectBundle:Default:view }
    requirements:
      id: '\d+'

book_edit:
    path: /{id}/edit
    defaults: { _controller: projectBundle:Default:edit }
    requirements:
      id: '\d+'

book_search:
    path: /search/{word}
    defaults: { _controller: projectBundle:Default:search}
