book_list:
    path:     /
    defaults: { _controller: projectBundle:Default:index }

book_add:
    path: /add_book
    defaults: { _controller: projectBundle:Default:add }

book_view:
    path:     /{id}
    defaults: { _controller: projectBundle:Default:view }
    requirements:
      id: '\d+'

book_edit:
    path: /edit/{id}
    defaults: { _controller: projectBundle:Default:edit }
    requirements:
      id: '\d+'

book_delete:
    path: /delete/{id}
    defaults: { _controller: projectBundle:Default:delete}
    requirements:
        id: '\d+'

#попробуй взять значения из get/post, а не через {word}
book_search:
    path: /search/{word}
    defaults: { _controller: projectBundle:Default:search}

publishing_house_edit:
    path: /rename_house
    defaults: { _controller: projectBundle:Default:renameHouse}

publishing_house_add:
    path: /add_house
    defaults: { _controller: projectBundle:Default:addHouse}

publishing_house_delete:
    path: /delete_house/{id}
    defaults: { _controller: projectBundle:Default:deleteHouse}

login:
  path: /login
  defaults: { _controller: projectBundle:Security:login}

login_check:
  path: /login_check
  defaults: { _controller: projectBundle:Security:loginCheck}

logout:
  path: /logout
  defaults: { _controller: projectBundle:Security:logout}

register:
  path: /register
  defaults: { _controller: projectBundle:Default:register}
