book_list:
    path:     /
    defaults: { _controller: projectBundle:Default:index }

book_add:
    path: /add_book
    defaults: { _controller: projectBundle:Default:add }

book_view:
    path:     /{id}
    defaults: { _controller: projectBundle:Default:view }
    requirements:
      id: '\d+'

book_top50:
    path: /top50
    defaults: { _controller: projectBundle:Default:getTop50 }

book_edit:
    path: /edit/{id}
    defaults: { _controller: projectBundle:Default:edit }
    requirements:
      id: '\d+'

book_delete:
    path: /delete/{id}
    defaults: { _controller: projectBundle:Default:delete}
    requirements:
        id: '\d+'

book_add_img:
    path: /book_add_img/{id}
    defaults: { _controller: projectBundle:Default:bookAddImg}
    requirements:
        id: '\d+'

book_delete_img:
    path: /delete_cover
    defaults: { _controller: projectBundle:Default:deleteCover}

book_search:
    path: /search
    defaults: { _controller: projectBundle:Default:search}

publishing_house_edit:
    path: /rename_house
    defaults: { _controller: projectBundle:Default:renameHouse}

publishing_house_add:
    path: /add_house
    defaults: { _controller: projectBundle:Default:addHouse}

publishing_house_delete:
    path: /delete_house/{id}
    defaults: { _controller: projectBundle:Default:deleteHouse}

login:
  path: /login
  defaults: { _controller: projectBundle:Security:login}

login_check:
  path: /login_check
  defaults: { _controller: projectBundle:Security:loginCheck}

logout:
  path: /logout
  defaults: { _controller: projectBundle:Security:logout}

register:
  path: /register
  defaults: { _controller: projectBundle:Default:register}

users_edit:
  path: /user_edit
  defaults: { _controller: projectBundle:User:userIndex}

flip_user_right:
  path: /user_right
  defaults: { _controller: projectBundle:User:flipUserRole}

flip_user_ban:
  path: /user_ban
  defaults: { _controller: projectBundle:User:flipBan}

do_like:
  path: /like
  defaults: { _controller: projectBundle:Default:like}

delete_comment:
  path: /delete_comment
  defaults: { _controller: projectBundle:Default:deleteComment }