book_list:
    path:     /
    defaults: { _controller: projectBundle:Default:index }

book_add:
    path: /add_book
    defaults: { _controller: projectBundle:Default:add }

book_view:
    path:     /{id}
    defaults: { _controller: projectBundle:Default:view }
    requirements:
      id: '\d+'

book_edit:
    path: /{id}/edit
    defaults: { _controller: projectBundle:Default:edit }
    requirements:
      id: '\d+'

book_delete:
    path: /{id}/delete
    defaults: { _controller: projectBundle:Default:delete}
    requirements:
        id: '\d+'

book_search:
    path: /search/{word}
    defaults: { _controller: projectBundle:Default:search}

publishing_house_edit:
    path: /rename_house
    defaults: { _controller: projectBundle:Default:renameHouse}

publishing_house_add:
    path: /add_house
    defaults: { _controller: projectBundle:Default:addHouse}

publishing_house_delete:
    path: /{id}/delete_house
    defaults: { _controller: projectBundle:Default:deleteHouse}

login:
  path: /login
  defaults: { _controller: projectBundle:Security:login}

register:
  path: /register
  defaults: { _controller: projectBundle:Default:register}
